/**
 * Test Cases page — View all test cases across projects.
 */

import { useEffect, useState } from "react";
import { ClipboardCheck } from "lucide-react";
import { Card, CardBody, CardHeader } from "../components/common/Card";
import { StatusBadge } from "../components/common/StatusBadge";
import { EmptyState } from "../components/common/EmptyState";
import { Loader } from "../components/common/Loader";
import { Modal } from "../components/common/Modal";
import { truncateText, formatDate } from "../utils/formatters";
import api from "../utils/api";

export function TestCasesPage() {
  const [testCases, setTestCases] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState(null);

  useEffect(() => {
    api.get("/testcases/")
      .then((res) => setTestCases(Array.isArray(res.data) ? res.data : []))
      .catch(() => setTestCases([]))
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <Loader />;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Test Cases</h1>
        <p className="text-gray-500 mt-1">{testCases.length} test case{testCases.length !== 1 ? "s" : ""} generated by AI.</p>
      </div>

      {testCases.length === 0 ? (
        <EmptyState
          icon={ClipboardCheck}
          title="No test cases yet"
          description="Generate test cases by uploading and analyzing a document in a project."
        />
      ) : (
        <Card>
          <CardBody className="p-0">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-left text-gray-500 border-b border-gray-200 bg-gray-50">
                    <th className="px-6 py-3 font-medium">ID</th>
                    <th className="px-6 py-3 font-medium">Scenario</th>
                    <th className="px-6 py-3 font-medium">Type</th>
                    <th className="px-6 py-3 font-medium">Status</th>
                    <th className="px-6 py-3 font-medium">Created</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {testCases.map((tc) => (
                    <tr
                      key={tc.id}
                      className="hover:bg-indigo-50/50 cursor-pointer transition-colors"
                      onClick={() => setSelected(tc)}
                    >
                      <td className="px-6 py-3 font-mono text-xs text-gray-500">{tc.test_case_id}</td>
                      <td className="px-6 py-3 text-gray-900">{truncateText(tc.scenario, 80)}</td>
                      <td className="px-6 py-3"><StatusBadge status={tc.case_type} /></td>
                      <td className="px-6 py-3"><StatusBadge status={tc.status} /></td>
                      <td className="px-6 py-3 text-gray-500 text-xs">{formatDate(tc.created_at)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardBody>
        </Card>
      )}

      {/* Detail Modal */}
      <Modal isOpen={!!selected} onClose={() => setSelected(null)} title={selected?.test_case_id || ""} size="lg">
        {selected && (
          <div className="space-y-4">
            <div>
              <h4 className="text-sm font-medium text-gray-500">Scenario</h4>
              <p className="text-gray-900 mt-1">{selected.scenario}</p>
            </div>
            {selected.preconditions && (
              <div>
                <h4 className="text-sm font-medium text-gray-500">Preconditions</h4>
                <p className="text-gray-900 mt-1">{selected.preconditions}</p>
              </div>
            )}
            <div>
              <h4 className="text-sm font-medium text-gray-500 mb-2">Test Steps</h4>
              <div className="space-y-2">
                {selected.test_steps?.map((step, i) => (
                  <div key={i} className="flex gap-3 p-3 bg-gray-50 rounded-lg">
                    <span className="w-6 h-6 bg-indigo-100 text-indigo-700 rounded-full flex items-center justify-center text-xs font-bold shrink-0">
                      {step.step_number || i + 1}
                    </span>
                    <div>
                      <p className="text-sm text-gray-900">{step.action}</p>
                      <p className="text-xs text-gray-500 mt-0.5">Expected: {step.expected}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div>
              <h4 className="text-sm font-medium text-gray-500">Expected Result</h4>
              <p className="text-gray-900 mt-1">{selected.expected_result}</p>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}
